//
//  Constants.swift
//  SAPA-Native
//
//  Created by Brian Lai on 10/7/14.
//  Copyright (c) 2014 SAPA. All rights reserved.
//

import Foundation

let USERDEFAULTSEMAIL = "userEmail"
let USERDEFAULTSAGE = "userAge"
let USERDEFAULTSGENDER = "userGender"

let STATEQUESTIONS = [
	"In the past 5 minutes, how much have you been feeling motivated?",
	"In the past 5 minutes, how much have you been feeling cautious?",
	"In the past 5 minutes, how much have you been feeling comforting?",
	"In the past 5 minutes, how much have you been feeling cooperative?",
	"In the past 5 minutes, how much have you been feeling forgetful?",
	"In the past 5 minutes, how much have you been feeling hard-working?",
	"In the past 5 minutes, how much have you been feeling impulsive?",
	"In the past 5 minutes, how much have you been feeling insulting?",
	"In the past 5 minutes, how much have you been feeling messy?",
	"In the past 5 minutes, how much have you been feeling modest?",
	"In the past 5 minutes, how much have you been feeling orderly?",
	"In the past 5 minutes, how much have you been feeling postponing?",
	"In the past 5 minutes, how much have you been feeling prepared?",
	"In the past 5 minutes, how much have you been feeling procrasinating?",
	"In the past 5 minutes, how much have you been feeling pushy?",
	"In the past 5 minutes, how much have you been feeling rule-abiding?",
	"In the past 5 minutes, how much have you been feeling soft-hearted?",
	"In the past 5 minutes, how much have you been feeling sympathetic?",
	"In the past 5 minutes, how much have you been feeling tricky?",
	"In the past 5 minutes, how much have you been feeling trusting?",
	"In the past 5 minutes, how much have you been feeling trustworthy?",
	"In the past 5 minutes, how much have you been feeling wary?",
	"In the past 5 minutes, how much have you been feeling active?",
	"In the past 5 minutes, how much have you been feeling afraid?",
	"In the past 5 minutes, how much have you been feeling alert?",
	"In the past 5 minutes, how much have you been feeling angry?",
	"In the past 5 minutes, how much have you been feeling anxious?",
	"In the past 5 minutes, how much have you been feeling aroused?",
	"In the past 5 minutes, how much have you been feeling ashamed?",
	"In the past 5 minutes, how much have you been feeling astonished?",
	"In the past 5 minutes, how much have you been feeling at ease?",
	"In the past 5 minutes, how much have you been feeling at rest?",
	"In the past 5 minutes, how much have you been feeling attentive?",
	"In the past 5 minutes, how much have you been feeling blue?",
	"In the past 5 minutes, how much have you been feeling bored?",
	"In the past 5 minutes, how much have you been feeling calm?",
	"In the past 5 minutes, how much have you been feeling clutched up?",
	"In the past 5 minutes, how much have you been feeling content?",
	"In the past 5 minutes, how much have you been feeling delighted?",
	"In the past 5 minutes, how much have you been feeling depressed?",
	"In the past 5 minutes, how much have you been feeling determined?",
	"In the past 5 minutes, how much have you been feeling determined?",
	"In the past 5 minutes, how much have you been feeling distress?",
	"In the past 5 minutes, how much have you been feeling drowsy?",
	"In the past 5 minutes, how much have you been feeling dull?",
	"In the past 5 minutes, how much have you been feeling elated?",
	"In the past 5 minutes, how much have you been feeling energetic?",
	"In the past 5 minutes, how much have you been feeling energetic?",
	"In the past 5 minutes, how much have you been feeling enthusiastic?",
	"In the past 5 minutes, how much have you been feeling excited?",
	"In the past 5 minutes, how much have you been feeling fearful?",
	"In the past 5 minutes, how much have you been feeling frustrated?",
	"In the past 5 minutes, how much have you been feeling full of pep?",
	"In the past 5 minutes, how much have you been feeling gloomy?",
	"In the past 5 minutes, how much have you been feeling grouchy?",
	"In the past 5 minutes, how much have you been feeling guilty?",
	"In the past 5 minutes, how much have you been feeling hostile?",
	"In the past 5 minutes, how much have you been feeling idle?",
	"In the past 5 minutes, how much have you been feeling inactive?",
	"In the past 5 minutes, how much have you been feeling inspired?",
	"In the past 5 minutes, how much have you been feeling intense?",
	"In the past 5 minutes, how much have you been feeling interested?",
	"In the past 5 minutes, how much have you been feeling irritable?",
	"In the past 5 minutes, how much have you been feeling jittery?",
	"In the past 5 minutes, how much have you been feeling lively?",
	"In the past 5 minutes, how much have you been feeling lonely?",
	"In the past 5 minutes, how much have you been feeling nervous?",
	"In the past 5 minutes, how much have you been feeling placid?",
	"In the past 5 minutes, how much have you been feeling proud?",
	"In the past 5 minutes, how much have you been feeling quiescent?",
	"In the past 5 minutes, how much have you been feeling quiet?",
	"In the past 5 minutes, how much have you been feeling relaxed?",
	"In the past 5 minutes, how much have you been feeling sad?",
	"In the past 5 minutes, how much have you been feeling satisfied?",
	"In the past 5 minutes, how much have you been feeling scared?",
	"In the past 5 minutes, how much have you been feeling serene?",
	"In the past 5 minutes, how much have you been feeling sleepy?",
	"In the past 5 minutes, how much have you been feeling sluggish?",
	"In the past 5 minutes, how much have you been feeling sorry?",
	"In the past 5 minutes, how much have you been feeling still?",
	"In the past 5 minutes, how much have you been feeling strong?",
	"In the past 5 minutes, how much have you been feeling surprise?",
	"In the past 5 minutes, how much have you been feeling tense?",
	"In the past 5 minutes, how much have you been feeling tired?",
	"In the past 5 minutes, how much have you been feeling tranquil?",
	"In the past 5 minutes, how much have you been feeling unhappy?",
	"In the past 5 minutes, how much have you been feeling upset?",
	"In the past 5 minutes, how much have you been feeling vigorous?",
	"In the past 5 minutes, how much have you been feeling wakeful?",
	"In the past 5 minutes, how much have you been feeling wide awake?",
	"In the past 5 minutes, how much have you been feeling adventurous?",
	"In the past 5 minutes, how much have you been feeling apathetic?",
	"In the past 5 minutes, how much have you been feeling confident?",
	"In the past 5 minutes, how much have you been feeling curious?",
	"In the past 5 minutes, how much have you been feeling decisive?",
	"In the past 5 minutes, how much have you been feeling dedicated?",
	"In the past 5 minutes, how much have you been feeling driven?",
	"In the past 5 minutes, how much have you been feeling exposed?",
	"In the past 5 minutes, how much have you been feeling fearful?",
	"In the past 5 minutes, how much have you been feeling frightened?",
	"In the past 5 minutes, how much have you been feeling fun-seeking?",
	"In the past 5 minutes, how much have you been feeling half-hearted?",
	"In the past 5 minutes, how much have you been feeling indecisive?",
	"In the past 5 minutes, how much have you been feeling indifferent?",
	"In the past 5 minutes, how much have you been feeling interested?",
	"In the past 5 minutes, how much have you been feeling perceptive?",
	"In the past 5 minutes, how much have you been feeling persistent?",
	"In the past 5 minutes, how much have you been feeling receptive?",
	"In the past 5 minutes, how much have you been feeling resolute?",
	"In the past 5 minutes, how much have you been feeling responsive?",
	"In the past 5 minutes, how much have you been feeling safe?",
	"In the past 5 minutes, how much have you been feeling secure?",
	"In the past 5 minutes, how much have you been feeling self-doubting?",
	"In the past 5 minutes, how much have you been feeling spontaneous?",
	"In the past 5 minutes, how much have you been feeling susceptible?",
	"In the past 5 minutes, how much have you been feeling tireless?",
	"In the past 5 minutes, how much have you been feeling underperforming?",
	"In the past 5 minutes, how much have you been feeling wavering?",
	"In the past 5 minutes, how much have you been feeling worrisome?"
]

let HEIGHTOPTIONS = [
	"less than 4ft (122cm)",
	"4ft 0in (122cm)",
	"4ft 1in (124cm)",
	"4ft 2in (127cm)",
	"4ft 3in (130cm)",
	"4ft 4in (132cm)",
	"4ft 5in (135cm)",
	"4ft 6in (137cm)",
	"4ft 7in (140cm)",
	"4ft 8in (142cm)",
	"4ft 9in (145cm)",
	"4ft 10in (147cm)",
	"4ft 11in (150cm)",
	"5ft 0in (152cm)",
	"5ft 1in (155cm)",
	"5ft 2in (157cm)",
	"5ft 3in (160cm)",
	"5ft 4in (163cm)",
	"5ft 5in (165cm)",
	"5ft 6in (168cm)",
	"5ft 7in (170cm)",
	"5ft 8in (173cm)",
	"5ft 9in (175cm)",
	"5ft 10in (178cm)",
	"5ft 11in (180cm)",
	"6ft 0in (183cm)",
	"6ft 1in (185cm)",
	"6ft 2in (188cm)",
	"6ft 3in (191cm)",
	"6ft 4in (193cm)",
	"6ft 5in (196cm)",
	"6ft 6in (198cm)",
	"6ft 7in (201cm)",
	"6ft 8in (203cm)",
	"6ft 9in (206cm)",
	"6ft 10in (208cm)",
	"6ft 11in (211cm)",
	"7ft 0in (213cm)",
	"more than 7ft (213cm)"
];

let WEIGHTOPTIONS = [
	"below 80 lbs (below 36 kg)",
	"80 - 85 lbs (36 - 39 kg)",
	"85 - 90 lbs (39 - 41 kg)",
	"90 - 95 lbs (41 - 43 kg)",
	"95 - 100 lbs (43 - 45 kg)",
	"100 - 105 lbs (45 - 48 kg)",
	"105 - 110 lbs (48 - 50 kg)",
	"110 - 115 lbs (50 - 52 kg)",
	"115 - 120 lbs (52 - 54 kg)",
	"120 - 125 lbs (54 - 57 kg)",
	"125 - 130 lbs (57 - 59 kg)",
	"130 - 135 lbs (59 - 61 kg)",
	"135 - 140 lbs (61 - 64 kg)",
	"140 - 145 lbs (64 - 66 kg)",
	"145 - 150 lbs (66 - 68 kg)",
	"150 - 155 lbs (68 - 70 kg)",
	"155 - 160 lbs (70 - 73 kg)",
	"160 - 165 lbs (73 - 75 kg)",
	"165 - 170 lbs (75 - 77 kg)",
	"170 - 175 lbs (77 - 79 kg)",
	"175 - 180 lbs (79 - 82 kg)",
	"180 - 185 lbs (82 - 84 kg)",
	"185 - 190 lbs (84 - 86 kg)",
	"190 - 195 lbs (86 - 88 kg)",
	"195 - 200 lbs (88 - 91 kg)",
	"200 - 205 lbs (91 - 93 kg)",
	"205 - 210 lbs (93 - 95 kg)",
	"210 - 215 lbs (95 - 98 kg)",
	"215 - 220 lbs (98 - 100 kg)",
	"220 - 225 lbs (100 - 102 kg)",
	"225 - 230 lbs (102 - 104 kg)",
	"230 - 235 lbs (104 - 107 kg)",
	"235 - 240 lbs (107 - 109 kg)",
	"240 - 245 lbs (109 - 111 kg)",
	"245 - 250 lbs (111 - 113 kg)",
	"250 - 255 lbs (113 - 116 kg)",
	"255 - 260 lbs (116 - 118 kg)",
	"260 - 265 lbs (118 - 120 kg)",
	"265 - 270 lbs (120 - 122 kg)",
	"270 - 275 lbs (122 - 125 kg)",
	"275 - 280 lbs (125 - 127 kg)",
	"280 - 285 lbs (127 - 129 kg)",
	"285 - 290 lbs (129 - 132 kg)",
	"290 - 295 lbs (132 - 134 kg)",
	"295 - 300 lbs (134 - 136 kg)",
	"above 300 lbs (above 136 kg)"
]

let RELATIONSHIPSTATUSOPTIONS = [
	"Single",
	"In a relationship"
]

let MARITALSTATUSOPTIONS = [
	"Never married",
	"Married",
	"Domestic Partnership",
	"Divorced & Single",
	"Divorced & Remarried",
	"Widowed & Single",
	"Widowed & Remarried"
]

let EXERCISEOPTIONS = [
	"Very rarely or never",
	"Less than once a month",
	"Less than once a week",
	"1 or 2 times a week",
	"3 to 5 times a week",
	"More than 5 times a week"
]

let SMOKINGOPTIONS = [
	"Never in my life",
	"Not in the last year",
	"Less than once a month",
	"Less than once a week",
	"1 to 3 days a week",
	"Most days",
	"Everyday (5 or less times)",
	"Up to 20 times a day",
	"More than 20 times a day"
]

let COUNTRYOPTIONS = [
	"USA",
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Borneo",
	"Bosnia Herzogovinia",
	"Botswana",
	"Brazil",
	"British Indian Ocean Territory",
	"British Virgin Islands",
	"Brunei",
	"Bulgaria",
	"Burkina Fasso",
	"Burma - Union of Myanmar",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo (The Democratic Republic of the Congo)",
	"Congo (The Republic of the Congo)",
	"Cook Islands",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"East Timor",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Faroe Islands",
	"Falkland Islands",
	"Federated States of Micronesia",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guinea-Bissau",
	"Guinea",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Ivory Coast (Republic of Côte d'Ivoire)",
	"Jamaica",
	"Japan",
	"Johnston Island",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kosovo",
	"Kuwait",
	"Kyrgystan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macau (Macao)",
	"Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Midway Islands",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands Antilles",
	"Netherlands",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"North Korea (Democratic People's Republic of Korea)",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestinian Territory",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairn Islands",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Reunion",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Helena",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Pierre and Miquelon",
	"Saint Vincent and Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea (Republic of Korea)",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria (Syrian Arab Republic)",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"U.S. Virgin Islands",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Wake Island",
	"Wallis and Futuna Islands",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]

let STATEOPTIONS = [
	"Alabama",
	"Alaska",
	"Arizona",
	"Arkansas",
	"California",
	"Colorado",
	"Connecticut",
	"Delaware",
	"District of Columbia",
	"Florida",
	"Georgia",
	"Hawaii",
	"Idaho",
	"Illinois",
	"Indiana",
	"Iowa",
	"Kansas",
	"Kentucky",
	"Louisiana",
	"Maine",
	"Maryland",
	"Massachusetts",
	"Michigan",
	"Minnesota",
	"Mississippi",
	"Missouri",
	"Montana",
	"Nebraska",
	"Nevada",
	"New Hampshire",
	"New Jersey",
	"New Mexico",
	"New York",
	"North Carolina",
	"North Dakota",
	"Ohio",
	"Oklahoma",
	"Oregon",
	"Pennsylvania",
	"Rhode Island",
	"South Carolina",
	"South Dakota",
	"Tennessee",
	"Texas",
	"Utah",
	"Vermont",
	"Virginia",
	"Washington",
	"West Virginia",
	"Wisconsin",
	"Wyoming"
]